config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :mails, only: [:create]
    resources :messages, only: [:index] do
      resources :attachments, only: [:show]
    end
    resources :contacts, only: [:index]

    post '/ping', to: 'commands#ping'
    post '/message-list', to: 'commands#message_list'
    post '/message-get', to: 'commands#message_get'
    post '/message-create', to: 'commands#message_create'
    post '/web-notification-enable', to: 'commands#web_notification_enable'
    post '/web-notification-disable', to: 'commands#web_notification_disable'
    post '/web-notification-status', to: 'commands#web_notification_status'
  end

  namespace :app do
    root 'messages#index'
    resources :messages, only: [:index, :show, :new, :create] do
      resource :content, only: [:show]
    end
    resources :shared_messages, only: [:show]
    resource :web_notification, only: [:create, :destroy]

    resource :settings, only: [:show, :update]
  end

  namespace :app_v2 do
    root 'pages#index'
    get '*path', to: 'pages#index'
  end


  resources :wannabe_users, only: [:create]

  get   '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'

  get   '/signin',  to: 'sessions#new'
  post  '/signin',  to: 'sessions#create'
  post  '/signout', to: 'sessions#destroy'

  get   '/service-worker.js', to: 'service_worker#service_worker'
  get   '/manifest.json',     to: 'service_worker#manifest'

  get   '/:id', to: 'pages#show', as: :page

  root  'pages#show', id: 'home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auth_token.rb
class AuthToken
  def initialize(user)
    @user = user
  end

  def value
    return @user.auth_token if @user.auth_token

    @user.auth_token = SecureRandom.hex(32)
    @user.save

    @user.auth_token
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates :email, presence: true

  scope :search, -> (input) {
    query = "%#{sanitize_sql_like(input)}%"
    where('email like :query or name like :query', query: query)
  }

  def as_json(options = {})
    { email: email, name: name }
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/email.rb
class Email < SimpleDelegator
  def html_part?
    html_part.present?
  end

  def text_part?
    text_part.present?
  end

  def html_body
    html_part&.decoded || text_part&.decoded || body.to_s
  end

  def senders
    self[:from]&.addrs || []
  end

  def cc_addresses
    self[:cc]&.addrs || []
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :message_tags
  has_many :tags, through: :message_tags
  has_one :open_token

  validates :from, presence: true
  validates :to, presence: true
  validates :data, presence: true

  scope :within_time_range, ->(time_range) {
    where(Message.arel_table[:created_at].between(time_range.to_range))
  }

  scope :on_date, ->(date) {
    where("date(created_at) = date(?)", date)
  }

  def parsed
    @parsed ||= Email.new(Mail.read_from_string(data))
  end

  def email
    parsed
  end

  def assign!(user)
    update(user: user)
  end

  def tag_with!(name:)
    tag = Tag.find_by(name: name)
    message_tags.create!(tag: tag)
  end

  def read!
    return if read?

    touch(:read_at)
  end

  def read?
    read_at.present?
  end

  def find_attachment(filename)
    parsed.attachments.find { |a| a.filename == filename }
  end

  def as_json(options = {})
    from_value = parsed.senders.map do |sender|
      { name: sender.display_name, address: sender.address }
    end
    tags_value = tags.map { |tag| { name: tag.name, color: tag.color } }

    attachments = parsed.attachments.map do |attachment|
      { filename: attachment.filename }
    end

    {
      id: id,
      subject: parsed.subject,
      read: read?,
      from: from_value,
      arrived_at: created_at,
      tags: tags_value,
      attachments: attachments
    }
  end
end

app/models/message_tag.rb
class MessageTag < ApplicationRecord
  belongs_to :message
  belongs_to :tag
end

app/models/open_token.rb
class OpenToken < ApplicationRecord
  belongs_to :message
end

app/models/settings.rb
class Settings
  include ActiveModel::Model

  attr_accessor :web_notification

  def self.load(user)
    Settings.new(web_notification: user.web_notification_enabled?)
  end

  def update(user)
    update_web_notification(user)
  end

  private

  def update_web_notification(user)
    return if user.web_notification_enabled? == web_notification

    if web_notification

    else

    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :message_tags
  has_many :messages, through: :messaga_tags
  has_many :user_tags
  has_many :users, through: :user_tags
end

app/models/time_range.rb
class TimeRange
  NAMES = %w[today yesterday this_week last_week].freeze
  STARTS_AT = {
    'today' => -> { Time.now.utc.beginning_of_day },
    'yesterday' => -> { Time.now.utc.beginning_of_day - 1.day },
    'this_week' => -> { Time.now.utc.at_beginning_of_week },
    'last_week' => -> { Time.now.utc.at_beginning_of_week - 7.days }
  }.freeze
  ENDS_AT = {
    'today' => -> { Time.now.utc },
    'yesterday' => -> { Time.now.utc.beginning_of_day },
    'this_week' => -> { Time.now.utc.at_end_of_week },
    'last_week' => -> { Time.now.utc.at_end_of_week - 7.days }
  }.freeze

  def initialize(name)
    raise 'Unsupported time frame' unless NAMES.include?(name)

    @name = name
  end

  def starts_at
    STARTS_AT[@name].call
  end

  def ends_at
    ENDS_AT[@name].call
  end

  def to_range
    starts_at..ends_at
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  STATE = [
    'waiting-list',
    'active'
  ].freeze

  has_many  :messages,          dependent: :destroy
  has_many  :user_tags,         dependent: :destroy
  has_one   :web_notification,  dependent: :destroy
  has_one   :workspace,         dependent: :destroy
  has_many  :contacts,          dependent: :destroy

  has_many  :tags,              through: :user_tags

  validates :address, presence: true
  validates :state, inclusion: { in: STATE }, allow_nil: true

  def to
    "<#{address}>"
  end

  def web_notification_enabled?
    web_notification.present?
  end
end

app/models/user_tag.rb
class UserTag < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/models/wannabe_user.rb
class WannabeUser < ApplicationRecord
  validates :email, presence: true, uniqueness: true
end

app/models/web_notification.rb
class WebNotification < ApplicationRecord
  belongs_to :user

  validates :endpoint,    presence: true
  validates :p256dh_key,  presence: true
  validates :auth_key,    presence: true
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :slug, presence: true, uniqueness: true
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
  before_action :set_raven_context

  private

  def set_raven_context
    # Add this when we have session
    # Raven.user_context(id: session[:current_user_id])
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    if valid_page_name?
      render page_name, layout: 'web'
    else
      not_found!
    end
  end

  private

  def page_name
    params[:id]
  end

  def valid_page_name?
    %w[home thankyou pricing support sus].include? params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_invite_token

  def new
    @user = User.new
  end

  def create
    result = User::Register.call(user_params)

    if result.success?
      track_signup_event
      redirect_to root_url
    else
      @user = result.user
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def check_invite_token
    not_found! if User.find_by(invite_token: params[:invite_token]).nil?
  end

  def track_signup_event
    ahoy.track('sign_up')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/app/shared/_header.html.erb
<div class="mx-screen bg-white o-shadow"
  data-controller="header"
>
  <div class="container mx-auto h-16 flex items-center">
    <div class="w-8/12 md:w-1/12">
      <%= link_to 'Outpostr', app_root_path, class: 'text-lg px-5' %>
    </div>
    <div class="w-7/12 hidden md:flex">
      <%= render 'app/shared/search' %>
    </div>


    <%# Start Right Menu %>
    <div class="w-4/12 hidden text-gray-700 md:flex">
      <div class="w-2/4">
      </div>

      <div class="w-1/4">
        <%= link_to new_app_message_path,
          class: 'cursor-pointer block bg-white h-16 hover:bg-gray-100 flex items-center' do %>
          <div class="w-full text-center">New Mail</div>
        <% end %>
      </div>

      <div class="w-1/4 drop-down">
        <a
          href='#'
          class="cursor-pointer block bg-white h-16 hover:bg-gray-100 flex items-center drop-down"
          data-action="click->header#openDesktopMenu"
        >
          <div class="w-full text-center drop-down">Menu</div>
        </a>

        <div class="hidden absolute bg-white o-shadow rounded-b" style="margin-left: -1.725rem;" data-target="header.desktopMenu">
          <%= link_to app_settings_path,
            class: 'cursor-pointer block bg-white h-12 hover:bg-gray-100 flex items-center px-10' do %>
            <div class="w-full text-center">Settings</div>
          <% end %>

          <%= button_to 'Sign Out', signout_path,
            class: 'cursor-pointer text-center w-full block bg-white h-12 hover:bg-gray-100 px-10',
            form_class: 'w-full hover:bg-gray-100' %>
        </div>
      </div>
    </div>
    <%# End Right Menu %>

    <%# Start Mobile Menu %>
    <div class="w-4/12 flex md:hidden flex-row-reverse px-5">
      <div class="border p-1 rounded cursor-pointer o-shadow" data-action="click->header#openMobileMenu" >
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="-5 -7 24 24" width="24" height="24" preserveAspectRatio="xMinYMin" class="jam jam-menu"><path d='M1 0h5a1 1 0 1 1 0 2H1a1 1 0 1 1 0-2zm7 8h5a1 1 0 0 1 0 2H8a1 1 0 1 1 0-2zM1 4h12a1 1 0 0 1 0 2H1a1 1 0 1 1 0-2z' /></svg>
      </div>

      <div class="bg-white hidden w-full h-full top-0 left-0 z-30" data-target="header.mobileMenu">
        <div class="flex flex-col">
          <div class="text-right">
            <div
              class="float-right cursor-pointer p-8"
              data-action="click->header#closeMobileMenu"
            >
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="-6 -6 24 24" width="24" height="24" preserveAspectRatio="xMinYMin" class="jam jam-close"><path d='M7.314 5.9l3.535-3.536A1 1 0 1 0 9.435.95L5.899 4.485 2.364.95A1 1 0 1 0 .95 2.364l3.535 3.535L.95 9.435a1 1 0 1 0 1.414 1.414l3.535-3.535 3.536 3.535a1 1 0 1 0 1.414-1.414L7.314 5.899z' /></svg>
            </div>
          </div>

          <div class="py-8 pt-10">
            <%= link_to new_app_message_path,
              class: 'cursor-pointer block text-xl flex items-center' do %>
              <div class="w-full text-center">New Mail</div>
            <% end %>
          </div>

          <div class="py-8">
            <%= link_to app_settings_path,
              class: 'cursor-pointer block text-xl flex items-center' do %>
              <div class="w-full text-center">Settings</div>
            <% end %>
          </div>

          <div class="py-8">
            <%= button_to 'Sign Out', signout_path,
              class: 'cursor-pointer text-center text-xl w-full block bg-white',
              form_class: 'w-full' %>
          </div>
        </div>
      </div>
    </div>
    <%# End Mobile Menu %>
  </div>
</div>

app/views/app/shared/_search.html.erb
<% if $rollout.active?(:search, Current.user) %>
  <div class="w-full relative">
    <input
      name="query"
      placeholder="type to search"
      class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight bg-gray-100 focus:bg-white"
    />
    <div class="hidden bg-white w-full border-l border-r border-b absolute rounded-b py-2 px-3">
      <ul>
        <li class="pb-2">Test</li>
        <li>Test 2</li>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/app_v2.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="manifest" href="/manifest.json">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link
      rel="apple-touch-icon"
      sizes="512x512"
      href="<%= image_path('web_hi_res_512.png') %>"
    >
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">

    <title>Outpostr</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="//cdn.quilljs.com/1.3.6/quill.bubble.css">
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

    <script type="text/javascript">
      <%
        key = Base64.urlsafe_decode64(
          Rails.application.credentials.vapid_public_key
        ).bytes
        auth_token = AuthToken.new(@current_user).value
      %>
      window.vapidPublicKey = new Uint8Array(<%= key %>)
      window.authToken = '<%= auth_token %>'
    </script>
    <%= javascript_pack_tag 'application_v2' %>
    <%= stylesheet_pack_tag 'application_v2' %>
  </head>

  <body class="o-bg-gray">
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="manifest" href="/manifest.json">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link
      rel="apple-touch-icon"
      sizes="512x512"
      href="<%= image_path('web_hi_res_512.png') %>"
    >
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">

    <title>Outpostr</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400&display=swap" rel="stylesheet">

    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    <script type="text/javascript">
      <%
        key = Base64.urlsafe_decode64(
          Rails.application.credentials.vapid_public_key
        ).bytes
      %>
      window.vapidPublicKey = new Uint8Array(<%= key %>)
    </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/web.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="manifest" href="/manifest.json">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link
      rel="apple-touch-icon"
      sizes="512x512"
      href="<%= image_path('web_hi_res_512.png') %>"
    >
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">

    <title>Outpostr</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400&display=swap" rel="stylesheet">

    <%= javascript_pack_tag 'web' %>
    <%= stylesheet_pack_tag 'web' %>
  </head>

  <body>
    <div class="container mx-auto">
      <div class="flex p-4">
        <div class="logo text-xl w-1/2 md:pl-0">
          <%= link_to 'Outpostr', root_url %>
        </div>
        <nav class="w-1/2 text-right">
          <ul class="flex items-center text-gray-700">
            <li class="px-4 text-center">
              <%= link_to 'Support', page_path('support'), class: 'hover:o-text-red
                o-smooth hidden md:inline-block' %>
            </li>
            <li class="pl-4">
              <%= link_to 'Login', signin_path, class: 'block o-text-red o-border-red
                border rounded px-8 py-1 hover:o-bg-red o-smooth hover:text-white' %>
            </li>
          </ul>
        </nav>
      </div>
    </div>

    <%= yield %>

    <footer class="border-t border-gray-300">
      <div class="container mx-auto py-10 md:py-20">
        <div class="flex px-4 md:px-0">
          <div class="w-1/2">
            <div class="logo text-xl w-1/2 mb-2">Outpostr</div>
            <div class="py-1">
              <%= link_to 'Pricing', page_path('pricing'), class: 'hover:o-text-red
                o-smooth md:hidden' %>
            </div>
            <div class="py-1">
              <%= link_to 'Support', page_path('support'), class: 'hover:o-text-red
                o-smooth md:hidden' %>
            </div>
          </div>
          <div class="w-1/2 text-right">
            <a
              href="https://twitter.com/weareoutpostr"
              target="_blank"
              class="inline-block rounded-full bg-gray-300 hover:o-bg-red
              text-white fill-current p-2 o-smooth mr-2">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="-2 -4 24 24" width="24" height="24" preserveAspectRatio="xMinYMin" class="jam jam-twitter"><path d='M20 1.907a8.292 8.292 0 0 1-2.356.637A4.07 4.07 0 0 0 19.448.31a8.349 8.349 0 0 1-2.607.98A4.12 4.12 0 0 0 13.846.015c-2.266 0-4.103 1.81-4.103 4.04 0 .316.036.625.106.92A11.708 11.708 0 0 1 1.393.754a3.964 3.964 0 0 0-.554 2.03c0 1.403.724 2.64 1.824 3.363A4.151 4.151 0 0 1 .805 5.64v.05c0 1.958 1.415 3.591 3.29 3.963a4.216 4.216 0 0 1-1.08.141c-.265 0-.522-.025-.773-.075a4.098 4.098 0 0 0 3.832 2.807 8.312 8.312 0 0 1-5.095 1.727c-.332 0-.658-.02-.979-.056a11.727 11.727 0 0 0 6.289 1.818c7.547 0 11.673-6.157 11.673-11.496l-.014-.523A8.126 8.126 0 0 0 20 1.907z' /></svg>
            </a>
            <a
              href="mailto:hello@outpostr.com"
              class="inline-block rounded-full bg-gray-300 hover:o-bg-red
              text-white fill-current p-2 o-smooth">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="-2 -5 24 24" width="24" height="24" preserveAspectRatio="xMinYMin" class="jam jam-inbox"><path d='M2 5.702V12h16V5.702L15.039 2H4.96L2 5.702zM0 5l4-5h12l4 5v7a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V5zm13.874 2a4.002 4.002 0 0 1-7.748 0H2V5h16v2h-4.126zm-2.142 0H8.268a2 2 0 0 0 3.464 0z'/></svg>
            </a>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mx-auto">
  <div class="text-center px-4 md:px-0">
    <div class="pt-24">
      <h1 class="font-light text-4xl md:text-6xl mb-4 md:mb-8">
        Mail made for you
      </h1>
      <p class="font-light text-xl md:text-3xl text-gray-600">
        No hustle of setting up your mail server and
        <br class="hidden sm:block md:block"/>
        no sacrifice of privacy and control
      </p>
    </div>
  </div>
</div>

<%= form_with url: wannabe_users_url, method: :post do |f| %>
  <div class="container mx-auto">
    <div class="flex pt-16 flex-col px-4 md:flex-row md:w-1/2 mx-auto md:items-center">
      <div class="mb-4 md:w-2/3">
        <%= f.text_field :email,
           class: 'appearance-none w-full py-3 px-5 text-gray-700 leading-tight
           border rounded outline-none text-lg border-gray-500',
           placeholder: 'Your current email address' %>
      </div>
      <div class="mb-4 md:w-1/3 md:pl-2">
        <button
          type="submit"
          class="w-full py-3 px-5 text-white hover:text-white o-bg-red
          border o-border-red rounded text-lg o-smooth cursor-pointer">
          Upgrade My Mail
        </button>
      </div>
    </div>
  </div>
<% end %>

<div class="container mx-auto my-20 md:my-56">
  <div class="flex md:w-4/5 mx-auto flex-col md:flex-row">
    <div class="md:w-1/3 px-8 mb-8 md:mb-0">
      <h2 class="text-2xl mb-3">Your Freedom</h2>

      <p class="text-gray-800 text-lg font-light">
        No more vendor locking. You own every emails and every attachment. You can easily
        export and take all your data with you.
      </p>
    </div>
    <div class="md:w-1/3 px-8 mb-8 md:mb-0">
      <h2 class="text-2xl mb-3">Your Rules</h2>

      <p class="text-gray-800 text-lg font-light">
        You decided what is spam and we learn from you. We don't put you into a bucket with
        everyone.
      </p>
    </div>
    <div class="md:w-1/3 px-8 mb-8 md:mb-0">
      <h2 class="text-2xl mb-3">Your Data</h2>

      <p class="text-gray-800 text-lg font-light">
        You choose where to store your messages. Currently we offer locations in EU & US.
      </p>
    </div>
  </div>
</div>

<div class="my-20">
  <div class="container mx-auto">
    <div class="md:w-4/5 mx-auto justify-center px-4 sm:px-0 md:px-0">
      <div class="mb-8 md:w-2/5 md:pl-10">
        <h2 class="text-2xl mb-3">Email content is the king</h2>

        <p class="text-gray-800 text-lg font-light">
          Email client was designed to be an email first, not an advertisment first.
          Nothing stands between you and email content.
        </p>
      </div>
      <div class="md:w-full">
        <div
          class="p-1 pt-2 sm:pt-4 md:pt-8 bg-white rounded border shadow-xl o-smooth">
          <img
            src="<%= asset_path('shot_3.png') %>"
            class="border" />
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/support.html.erb
<div class="container mx-auto">
  <div class="text-center px-4 md:px-0">
    <div class="pt-16">
      <h1 class="text-4xl md:text-3xl mb-4 md:mb-2">
        Support
      </h1>
      <p class="font-light text-xl md:text-xl text-gray-600">
        We are always happy to help and answer your questions
      </p>
    </div>
  </div>
</div>

<div class="container mx-auto my-32">
  <div class="w-2/4 mx-auto text-center">
    <p class="text-lg">Write us an email to:</p>
    <p class="py-4 text-2xl">
      <a href="mailto:hello@outpostr.com">hello@outpostr.com</a>
    </p>
  </div>
</div>

app/views/pages/sus.html.erb
<div style="background-color: #E06F3B">
  <div class="container mx-auto text-white">
    <div class="text-center px-4 md:px-0">
      <div class="py-16">
        <h1 class="text-4xl md:text-3xl mb-4 md:mb-2">
          Free Email for Your Company
        </h1>
        <p class="font-light text-xl md:text-xl">
          Only for Startup School Companies
        </p>
      </div>
    </div>
  </div>
</div>

<div class="container mx-auto">
  <div class="px-4 md:px-0 md:w-2/4 mx-auto">
    <div class="py-16">
      <h2 class="text-3xl md:text-2xl mb-4 md:mb-2">
        What is it?
      </h1>
      <p class="text-lg mb-8">
        Outpostr provides free email service for your startup. In just a few steps
        you will go from having just an awesome domain name to having an awesome
        private email address.
      </p>

      <h2 class="text-3xl md:text-2xl mb-4 md:mb-2">
        Why do I need it?
      </h1>
      <p class="text-lg mb-8">
        Talking to your customers is one of the most important things startup should do.
        Mail is a first and primary communication channel for many companies and individuals.
        Email with your company's domain name adds credibility which is a key
        factor when you start.
      </p>

      <h2 class="text-3xl md:text-2xl mb-4 md:mb-2">
        How to get my private email address?
      </h1>
      <p class="text-lg mb-2">
        It's very simple. First, let's go through the checklist to see if you qualify.
      </p>
      <ul class="text-lg mb-2 pl-4">
        <li>1. You have a private domain</li>
        <li>2. You need an email that looks like: [name]@[my-domain.com]</li>
        <li>3. You have 30 minutes to join me on a call to go through an onboarding</li>
      </ul>
      <p class="text-lg mb-2">
        If you can tick all 3 points, fill in the form below and I will reach out shortly.
      </p>
    </div>
  </div>
</div>

<div class="bg-gray-100">
  <%= form_with url: wannabe_users_url, method: :post do |f| %>
    <div class="container mx-auto py-16">
      <div class="md:w-2/4 mx-auto">
        <div class="mb-8 text-center">
          <h2 class="text-2xl">Application Form</h2>
        </div>
        <div class="mb-8 px-4">
          <div class="mb-2">
            <%= f.label :name, class: 'text-xl' %>
          </div>
          <%= f.text_field :name,
            class: 'appearance-none w-full py-3 px-5 text-gray-700 leading-tight
            border rounded outline-none text-lg border-gray-500',
            placeholder: 'How would you like me to call you?' %>
        </div>

        <div class="mb-8 px-4">
          <div class="mb-2">
            <%= f.label :email, class: 'text-xl' %>
          </div>
          <%= f.text_field :email,
            class: 'appearance-none w-full py-3 px-5 text-gray-700 leading-tight
            border rounded outline-none text-lg border-gray-500',
            placeholder: 'Your current email address' %>
        </div>

        <div class="mb-8 px-4">
          <div class="mb-2">
            <%= f.label :company_name, class: 'text-xl' %>
          </div>
          <%= f.text_field :company_name,
            class: 'appearance-none w-full py-3 px-5 text-gray-700 leading-tight
            border rounded outline-none text-lg border-gray-500',
            placeholder: 'Monster Inc' %>
        </div>

        <div class="mb-8 px-4">
          <div class="mb-2">
            <%= f.label :domain_name, class: 'text-xl' %>
          </div>
          <%= f.text_field :domain_name,
            class: 'appearance-none w-full py-3 px-5 text-gray-700 leading-tight
            border rounded outline-none text-lg border-gray-500',
            placeholder: 'https://monster-inc.com' %>
        </div>

        <div class="mb-8 px-4">
          <div class="mb-2">
            <%= f.label :domain_hosting, class: 'text-xl' %>
          </div>
          <%= f.text_field :domain_hosting,
            class: 'appearance-none w-full py-3 px-5 text-gray-700 leading-tight
            border rounded outline-none text-lg border-gray-500 mb-1',
            placeholder: 'Ex: Cloudfront, AWS, DigitalOcean' %>
          <p class="text-gray-600">
            We use this information to make on-boarding process smooth as silk.
          </p>
        </div>

        <div class="md:w-1/2 mx-auto py-8 px-4">
          <button
            type="submit"
            class="w-full py-3 px-5 text-white hover:text-white o-bg-red
            border o-border-red rounded text-lg o-smooth cursor-pointer">
            I want my private email
          </button>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/thankyou.html.erb
<div class="container mx-auto mb-32">
  <div class="text-center px-4 md:px-0">
    <div class="pt-24">
      <h1 class="font-light text-4xl md:text-6xl mb-4 md:mb-8">
        Thank you
      </h1>
      <p class="font-light text-xl md:text-3xl text-gray-600">
        We will write you back shortly.
      </p>
    </div>
  </div>
</div>