config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :mails, only: [:create]
    resources :messages, only: [:index] do
      resources :attachments, only: [:show]
    end
    resources :contacts, only: [:index]

    post '/ping', to: 'commands#ping'
    post '/message-list', to: 'commands#message_list'
    post '/message-get', to: 'commands#message_get'
    post '/message-create', to: 'commands#message_create'
    post '/web-notification-enable', to: 'commands#web_notification_enable'
    post '/web-notification-disable', to: 'commands#web_notification_disable'
    post '/web-notification-status', to: 'commands#web_notification_status'
  end

  namespace :app do
    root 'messages#index'
    resources :messages, only: [:index, :show, :new, :create] do
      resource :content, only: [:show]
    end
    resources :shared_messages, only: [:show]
    resource :web_notification, only: [:create, :destroy]

    resource :settings, only: [:show, :update]
  end

  namespace :app_v2 do
    root 'pages#index'
    get '*path', to: 'pages#index'
  end


  resources :wannabe_users, only: [:create]

  get   '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'

  get   '/signin',  to: 'sessions#new'
  post  '/signin',  to: 'sessions#create'
  post  '/signout', to: 'sessions#destroy'

  get   '/service-worker.js', to: 'service_worker#service_worker'
  get   '/manifest.json',     to: 'service_worker#manifest'

  get   '/:id', to: 'pages#show', as: :page

  root  'pages#show', id: 'home'
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :message_tags
  has_many :tags, through: :message_tags
  has_one :open_token

  validates :from, presence: true
  validates :to, presence: true
  validates :data, presence: true

  scope :within_time_range, ->(time_range) {
    where(Message.arel_table[:created_at].between(time_range.to_range))
  }

  scope :on_date, ->(date) {
    where("date(created_at) = date(?)", date)
  }

  def parsed
    @parsed ||= Email.new(Mail.read_from_string(data))
  end

  def email
    parsed
  end

  def assign!(user)
    update(user: user)
  end

  def tag_with!(name:)
    tag = Tag.find_by(name: name)
    message_tags.create!(tag: tag)
  end

  def read!
    return if read?

    touch(:read_at)
  end

  def read?
    read_at.present?
  end

  def find_attachment(filename)
    parsed.attachments.find { |a| a.filename == filename }
  end

  def as_json(options = {})
    from_value = parsed.senders.map do |sender|
      { name: sender.display_name, address: sender.address }
    end
    tags_value = tags.map { |tag| { name: tag.name, color: tag.color } }

    attachments = parsed.attachments.map do |attachment|
      { filename: attachment.filename }
    end

    {
      id: id,
      subject: parsed.subject,
      read: read?,
      from: from_value,
      arrived_at: created_at,
      tags: tags_value,
      attachments: attachments
    }
  end
end

app/controllers/api/messages_controller.rb
module Api
  class MessagesController < ApplicationController
    protect_from_forgery with: :null_session
    before_action :authenticate_with_token

    def index
      @messages =
        if params[:when]
          @current_user
            .messages
            .includes(:tags)
            .on_date(Date.parse(params[:when]))
            .order(created_at: :desc)
        else
          @current_user
            .messages
            .includes(:tags)
            .order(created_at: :desc)
        end

      render json: { messages: @messages.as_json }
    end

    private

    def authenticate_with_token
      authenticate_with_http_basic do |auth_token|
        @current_user = User.find_by(auth_token: auth_token)
      end
    end
  end
end

app/controllers/app/messages_controller.rb
module App
  class MessagesController < ApplicationController
    before_action :require_authentication

    def index
      @messages =
        MessageService.list(user: Current.user, time_frame: time_frame)

      @unread_count = {
        today: message_count('today'),
        yesterday: message_count('yesterday')
      }
    end

    def show
      @message = MessageService.get(id: params[:id])
      @open_token = OneTimeOpenToken.generate(@message.id)
      @message.read!
      ahoy.track('message_open', id: @message.id)
    end

    def new
      @message = Message.new
      if params[:reply_to].present?
        @reply_to_message = MessageService.get(id: params[:reply_to])
        @open_token = OneTimeOpenToken.generate(@reply_to_message.id)
      end
    end

    def create
      create_message = CreateMessage.new

      create_message.subscribe(DeliverMessage.new, prefix: :on)

      create_message.on(:create_message_ok) { redirect_to app_messages_url }
      create_message.on(:create_message_error) { render :new }

      create_message.call(sender: Current.user, message: params[:message])
    end

    private

    def require_authentication
      redirect_to signin_url if Current.user.nil?
    end

    def time_frame
      params[:when] || 'today'
    end

    def message_count(time_frame)
      Message
        .within_time_range(TimeRange.new(time_frame))
        .where(user: Current.user, read_at: nil)
        .count
    end
  end
end

app/views/app/messages/_message.html.erb
<%= link_to app_message_path(message),
  class: 'text-grey-darkest no-underline',
  'data-controller': 'message-item',
  'data-action': 'click->message-item#click' do %>
  <% bg_color = message.read? ? 'bg-grey-lightest' : 'bg-white' %>

  <div class="py-3 pr-5 mb-2 rounded bg-white o-shadow">
    <div class="flex">
      <div class="w-1/12 flex items-center justify-center">
        <% bg_color = message.read? ? 'rgba(0, 0, 0, 0.10)' : '#EF5753' %>
        <div
          class="w-3 h-3 rounded-full"
          style="background-color: <%= bg_color %>"
          data-target="message-item.dot"
        ></div>
      </div>

      <div class="w-11/12">
        <div class="flex items-center">
          <div class="w-1/2 md:w-3/4 font-semibold">
            <% message.parsed.senders.each do |sender| %>
              <%= sender.display_name || sender.address %>
            <% end %>
          </div>
          <div class="w-1/2 md:w-1/4 text-gray-600 text-sm text-right font-light">
            <%= time_ago_in_words(message.created_at) %> ago
          </div>
        </div>
        <div class="flex items-center pb-3">
          <div class="w-full text-gray-800">
            <div class="truncate w-11/12">
              <%= message.parsed.subject %>
            </div>
          </div>
        </div>
        <div class="flex text-right text-sm">
          <% message.tags.each do |tag| %>
            <div class="inline-block px-3 rounded" style="background-color: <%= tag.color %>">
              <%= tag.name %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/app/messages/_notification_suggestion.html.erb
<div class="pt-4 pl-10">
  <div class="rounded p-4 bg-yellow-100 text-sm text-grey-darkest o-shadow" data-controller="notification">
    <h4 class="pb-3">Did you miss an important email?</h4>

    <p class="pb-2 ">
      Notification is the best way to make sure you won't miss that
      important email.
    </p>

    <p class="pb-6">
      You can always disable it in your settings in case it's too noisy.
    </p>

    <a
      href="#"
      class="block py-2 px-4 bg-yellow-500 rounded text-black no-underline w-full
             text-center fon"
      data-action="notification#turnOn"
    >
      Turn On Notifications
    </a>
  </div>
</div>

app/views/app/messages/_tag.html.erb
<li
  class="p-2"
  data-controller="tag"
  data-tag-name="<%= tag.name %>"
>
  <div class="flex items-center h-5 cursor-pointer" data-action="click->tag#select">
    <div class="pr-2">
      <div class="w-5 h-5 rounded-full" style="background-color: <%= tag.color %>"></div>
    </div>
    <div class="px-2 py-1 rounded"
          style="background-color: <%= @tag_names.include?(tag.name) ? tag.color : 'none' %>">
      <%= tag.name %>
    </div>
  </div>
</li>

app/views/app/messages/_tags.html.erb
<ul class="list-reset flex">
  <%= render partial: 'tag', collection: tags %>
</ul>

app/views/app/messages/_time_frame.html.erb
<ul class="flex list-reset text-base px-5">
  <li>
    <a
      href=""
      data-controller="time-frame"
      data-action="click->time-frame#select"
      data-time-frame-name="today"
      class="no-underline cursor-pointer hover:text-red-600 md:pr-8 pr-3 py-2 block text-grey-darker <%= (params[:when] == 'today') ? 'text-red-600' : 'text-grey-darker' %>">
      <% if $rollout.active?(:unread_mark, Current.user) %>
        <% if @unread_count[:today] != 0 %>
          <span class="text-sm bg-red-400 text-white inline-block w-2 h-2 text-center rounded-full">
          </span>
        <% else %>
          <span class="text-sm inline-block w-2 h-2 rounded-full"></span>
        <% end %>
      <% end %>
      Today
    </a>
  </li>
  <li>
    <a
      href=""
      data-controller="time-frame"
      data-action="click->time-frame#select"
      data-time-frame-name="yesterday"
      class="no-underline cursor-pointer hover:text-red-600 md:pr-8 pr-3 py-2 block text-grey-darker <%= (params[:when] == 'yesterday') ? 'text-red-600' : 'text-grey-darker' %>">
      <% if $rollout.active?(:unread_mark, Current.user) %>
        <% if @unread_count[:yesterday] != 0 %>
          <span class="text-sm bg-red-400 text-white inline-block w-2 h-2 text-center rounded-full">
          </span>
        <% else %>
          <span class="text-sm inline-block w-2 h-2 rounded-full"></span>
        <% end %>
      <% end %>
      Yesterday
    </a>
  </li>
  <li>
    <a
      href=""
      data-controller="time-frame"
      data-action="click->time-frame#select"
      data-time-frame-name="this_week"
      class="no-underline cursor-pointer hover:text-red-600 md:pr-8 pr-3 py-2 block text-grey-darker <%= (params[:when] == 'this_week') ? 'text-red-600' : 'text-grey-darker' %>">
      <% if $rollout.active?(:unread_mark, Current.user) %>
        <span class="text-sm inline-block w-2 h-2 rounded-full"></span>
      <% end %>
      This Week
    </a>
  </li>
  <li>
    <a
      href=""
      data-controller="time-frame"
      data-action="click->time-frame#select"
      data-time-frame-name="last_week"
      class="no-underline cursor-pointer hover:text-red-600 md:pr-10 pr-3 py-2 block text-grey-darker <%= (params[:when] == 'last_week') ? 'text-red-600' : 'text-grey-darker' %>">
      <% if $rollout.active?(:unread_mark, Current.user) %>
        <span class="text-sm inline-block w-2 h-2 rounded-full"></span>
      <% end %>
      Last Week
    </a>
  </li>
</ul>

app/views/app/messages/index.html.erb
<div class="min-h-screen" style="background-color: #FCFBFC">
  <%= render 'app/shared/header' %>

  <div class="container mx-auto flex pt-2 md:pt-6 mb-2 md:mb-4">
    <div class="md:w-1/12"></div>
    <div class="w-full md:w-7/12"><%= render 'time_frame' %></div>
  </div>

  <div class="container mx-auto flex justify-center pb-6">
    <div class="md:w-1/12"></div>
    <div class="w-full md:w-7/12">
      <% @messages.each do |message| %>
        <% cache message do %>
          <%= render 'message', message: message %>
        <% end%>
      <% end %>
    </div>
    <div class="hidden md:block w-4/12 pt-12">
      <% if $rollout.active?(:web_notification, Current.user) %>
        <% unless Current.user.web_notification_enabled? %>
          <%= render "notification_suggestion" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/app/messages/new.html.erb
<div class="min-h-screen" style="background-color: #FCFBFC">
  <%= render 'app/shared/header' %>

  <% if @reply_to_message.present? %>
    <div class="container mx-auto justify-center flex py-6">
      <div class="w-full md:w-2/3 bg-white p-5 rounded o-shadow">
        <iframe
          class="w-full"
          src="<%= app_message_content_url(@reply_to_message, open_token: @open_token) %>">
        </iframe>
      </div>
    </div>
  <% end %>

  <div class="container mx-auto justify-center flex py-6" data-controller="editor">
    <div class="md:w-1/12"></div>
    <div class="w-full md:w-8/12 bg-white py-5 px-8 rounded o-shadow">
      <%= form_with model: @message, url: app_messages_path do |form| %>
        <%= form.hidden_field :in_reply_to, value: @reply_to_message&.parsed&.message_id %>

        <div class="py-4 px-2">
          <%= form.text_field :subject,
                              value: @reply_to_message&.parsed&.subject,
                              placeholder: 'Enter subject',
                              class: 'w-full text-2xl',
                              'data-target': 'editor.subject' %>
        </div>

        <div id="editor-container" class="pb-6 px-2">
          <%= form.hidden_field :body, 'data-target': 'editor.content' %>
          <mail-editor></mail-editor>
        </div>

        <div class="border-t border-gray-200 pt-5 px-2 flex items-center">
          <div class="w-3/4">
            <%= form.text_field :to, value: @reply_to_message&.parsed&.from, placeholder: 'Recipients', class: 'w-full' %>
          </div>
          <div class="w-1/4 text-right">
            <button class="bg-gray-800 hover:bg-gray-700 text-white py-2 px-8 rounded">
              Send
            </button>
          </div>
        </div>

      <% end %>
    </div>
    <div class="hidden md:block w-3/12 pt-12"></div>
  </div>
</div>

app/views/app/messages/show.html.erb
<div class="min-h-screen" style="background-color: #FCFBFC">
  <%= render 'app/shared/header' %>

  <div class="container mx-auto flex pt-2 md:pt-6 mb-2 md:mb-4">
    <div class="md:w-1/12"></div>
    <div class="w-full md:w-11/12 px-5" data-controller="back-link">
      <%= link_to 'Back to list', app_root_path,
        'data-action' => 'click->back-link#goBack',
        class: 'py-2 inline-block'
      %>
    </div>
  </div>

  <div class="container mx-auto flex justify-center pb-6">
    <div class="md:w-1/12"></div>
    <div class="w-full md:w-8/12 bg-white rounded h-full overflow-hidden o-shadow">
      <div class="p-4 border-b border-gray-200">
        <div class="text-lg"><%= @message.parsed.subject %></div>
        <div class="text-sm text-gray-600">
          from
          <% @message.parsed.senders.each do |sender| %>
            <%= sender.display_name || sender.address %>
          <% end %>
        </div>
      </div>
      <div class="h-full">
        <iframe
          class="min-w-full block overflow-hidden"
          style="width: 1px;"
          src="<%= app_message_content_url(@message, open_token: @open_token) %>"
          sandbox="allow-top-navigation allow-scripts allow-same-origin"
          scrolling="no">
        </iframe>
        <script>
          window.addEventListener('message', function(event) {
            var params = JSON.parse(event.data);
            if (params.name === 'setHeight') {
              document.querySelector('iframe').style.height = params.value + 'px';
            }
          });
        </script>
      </div>
      <div class="p-4 border-t border-gray-100 text-right">
        <%= link_to 'Reply',
          new_app_message_path(reply_to: @message.id),
          class: 'bg-gray-900 hover:bg-gray-700 text-white py-2 px-8 rounded' %>
      </div>
    </div>
    <div class="hidden md:block w-3/12 pt-12"></div>
  </div>
</div>